### PR TITLE
(image): adds the starter modelling process image in Spanish

### PR DESCRIPTION
**Pull request by jlasoc1**
**Sumary**
This PR creates the domain-driven design starter process diagram in Spanish, and also adds a new folder under translations for Spanish content 

**Where the change occurs**
ddd-starter-modelling-process/translations/es/resources/

**Does it have test?**
N/A

### CODE REVIEW

**Comment by Max-Git** [comment]
Thanks!

**Comment by emgsilva** [comment]
Looking good @jlasoc1 (from my understanding of Spanish it seems like a good choice of names).

One remark, sometime in the past months we have changed the order of the "strategize" and "connect" stages. Can you align with that?

**Comment by Max-Git** [comment]
Oh yeah, thanks @emgsilva I totally forgot to look at the steps order! It would be nice ideed if all the pictures are aligned :)

**Comment by jlasoc1** [comment]
sure i'll do it ! 
thanks @emgsilva  and @Max-Git  !

**Pull request merged**
