### PR TITLE
(image): updates colored image of ddd modeling process with arrows

### PR DESCRIPTION
**Pull request by jlasoc1**
**Sumary**
This PR updates the domain-driven design starter process diagram with a colored one, with grey arrows. I'm opening this PR because I talked to @Max-Git and he liked the colored version and asked me to submit a PR

**Where the change occurs**
README.md file

**Does it have test?**
N/A

### CODE REVIEW

**Comment by emgsilva** [comment]
I like the coloring too, it makes things "jumps out" more into one's eyes.

Some little things I would propose to "refactor":
- `Define`: keep the canvas (Bounded Context Canvas) sketch/icon, instead of the new graphics... or mix/merge them? I think it is good to show that sort of tool and focus we do there.
- `Code`: try to still show the "Aggregate" diagram from the old diagram, which really shows an important aspect of that phase (and recommendation of using the Aggregate Design Canvas)
- `Organize`: maybe you could add three "circles" (teams), looks like there is something missing on the top-left part of the image :D 

Anyways, these are just small things (and maybe some are too literal and focused on the "tools" we use on each phase... but those popped out when I was looking at the colored diagram). I think in general color really highlights things in the diagram, good job @jlasoc1!

**Comment by jlasoc1** [comment]
> I like the coloring too, it makes things "jumps out" more into one's eyes.
> 
> Some little things I would propose to "refactor":
> 
> * `Define`: keep the canvas (Bounded Context Canvas) sketch/icon, instead of the new graphics... or mix/merge them? I think it is good to show that sort of tool and focus we do there.
> * `Code`: try to still show the "Aggregate" diagram from the old diagram, which really shows an important aspect of that phase (and recommendation of using the Aggregate Design Canvas)
> * `Organize`: maybe you could add three "circles" (teams), looks like there is something missing on the top-left part of the image :D
> 
> Anyways, these are just small things (and maybe some are too literal and focused on the "tools" we use on each phase... but those popped out when I was looking at the colored diagram). I think in general color really highlights things in the diagram, good job @jlasoc1!

I'll look into this, thank you for the feedback, sorry the late reply I'm in Chile timezone hahaha :)

**Comment by jlasoc1** [comment]
Hey folks, the PR was updated from the feedback comments of @emgsilva 😄 
thanks for pointing out those details, I almost missed the circled with the people hahaha 
I also modified the icons as requested, let me know if something else is needed if not, feel free to merge 🥳

**Comment by AlexZeitler** [comment]
Looks good to me - I like it! :+1:

**Comment by Max-Git** [comment]
I love that colored picture! 🤩 Thanks again @jlasoc1 ! Do you think it would be possible to add the subtitle sentence that was on the previous version? I think it adds some useful context on how to use the process that avoid people being too dogmatic about it. Thanks!

**Comment by NTCoding** [comment]
Honestly, I think is great. It's much better and more appealing with colour in my opinion. If there was 1 think I would change it would be the arrows, maybe use a slightly lighter grey and a bit of opacity so you can see the arrows overlapping a bit.

Is it too soon to ask @jlasoc1 to give this repo a makeover as well 😅? https://github.com/ddd-crew/welcome-to-ddd

**Review by AlexZeitler — APPROVED** [review]

**Comment by NTCoding** [comment]
@jlasoc1 feel free to merge this whenever you are ready and have finished reviewing the feedback. You should have permissions to do that.

**Comment by jlasoc1** [comment]
Wooow @NTCoding that repo looks amazing for a makeover hahaha, I'll take a look. My design skills have limits hahahah

**Comment by jlasoc1** [comment]
I'll merge the file @Max-Git if you want me to do any other change I can definitely post another PR, we can improve this as much as we want 🥳

**Comment by Max-Git** [comment]
Many thanks @jlasoc1 !!!

**Comment by mploed** [comment]
Thanks @jlasoc1 this looks amazing!

**Pull request merged**
