### PR TITLE
Similarities with whirlpool process

### PR DESCRIPTION
**Pull request by Max-Git**

### CODE REVIEW

**Comment by NTCoding** [comment]
Hi @Max-Git. Excellent initiative putting this together. Overall I think it's great. Maybe over time there are ways to improve it, but I definitely feel that this is good enough to be shared publicly.

If I had to put my finger on a few things I'd say:

1. Discover appears in 3 places which is correct but it may be worth adding some additional notes about how it differs in each scenario: e.g. discovery can be done at a very high-level (end-to-end business process), a granular level (e.g. designing a feature) and also for current states and possible future states as well.

2. "Connect" the sub-domains may not always happen if the model being developed is within a single sub-domain. Maybe there is some value in highlighting that this whirlpool process can apply at a strategic and tactical level?

I think it would be OK to publish the current version as-is. My two points above are maybe something that we think about for a while. Also, getting feedback and other perspectives will be valuable, too.

As a wishlist item: perhaps a blog post or video showing a concrete example of this. Or maybe we can do a meetup and do it together live.

**Review by NTCoding — APPROVED** [review]

**Comment by yellowbrickc** [comment]
Thanks for pinging me on Twitter @NTCoding , this is really a great idea and great visualisation @Max-Git!
I have one idea regarding the "discover"-points from Nick: a kind of zoom level could help. I just learned at kandddinsky about cloud-level with a cloud as emoji and about kite-level (emoji too). I found them very self-explaining and clear for everyone.

My suggestions are at the bottom. I would change "Walk through scenarios and events and states" with "Walk through scenarios and examples" and put "events and states" on the left side in the code-card.  What do you think?

**Comment by NTCoding** [comment]
> Thanks for pinging me on Twitter @NTCoding , this is really a great idea and great visualisation @Max-Git! I have one idea regarding the "discover"-points from Nick: a kind of zoom level could help. I just learned at kandddinsky about cloud-level with a cloud as emoji and about kite-level (emoji too). I found them very self-explaining and clear for everyone.
> 
> My suggestions are at the bottom. I would change "Walk through scenarios and events and states" with "Walk through scenarios and examples" and put "events and states" on the left side in the code-card. What do you think?

Hey @yellowbrickc I think the text was already there as part of Eric's whirlpool https://www.domainlanguage.com/ddd/whirlpool/

But I do like your thinking. You like to challenge everything and that's a good thing. Maybe the whirlpool can be improved as well? Possibly another PR thought?

**Comment by yellowbrickc** [comment]
I should have checked the original picture first 😊 

>This is not a development process. It should fit within most processes that iterate on the design.

After reading the explanation of the intention of this model and the blog post from @Baasie about his experience with it I think that those lists are not set, they are possibilities. Depending on the scope (tactical or strategic) it could include code or just pseudo-code or some example mapping. It is the continuation of the same idea you had @NTCoding with point 1. in your first comment. 

My suggestion is to change the introductory text to
`The picture below shows a possible overlap between the two processes.`
and merge it.

**Comment by Max-Git** [comment]
Thank you @yellowbrickc and @NTCoding for your observations.
I've updated the picture and the text according to your remarks.
There's still future and current state to be mentioned somehow, but I did not find the perfect way to do it yet :)

**Pull request merged**
