### PR TITLE
Put Stretegize before Connect

### PR DESCRIPTION
**Pull request by skleanthous**
closes: #35

This addresses the issue discussed in #35, which basically moves Strategize to come first before Connect.

I did not expand on why Strategize should come first, as the order was not explained before, and it seems that some discussion regarding messaging will happen in another issue later (see: [Nicks' comment in that thread](https://github.com/ddd-crew/ddd-starter-modelling-process/issues/35#issuecomment-1195688896))

### CODE REVIEW

**Comment by Max-Git** [comment]
It would be great if the image would reflect that change as well. Could you do that @skleanthous? Thanks!

**Comment by skleanthous** [comment]
@Max-Git which image is that? The whirlpool model actually has stragize first already 😄

**Comment by Max-Git** [comment]
That one: https://github.com/ddd-crew/ddd-starter-modelling-process/blob/master/resources/ddd-starter-modelling-process-colored.png 
Thanks!

**Comment by skleanthous** [comment]
Yes, will do 👍

**Review by Max-Git — APPROVED** [review]

**Review by Max-Git — APPROVED** [review]

**Comment by Max-Git** [comment]
Thanks!

**Pull request merged**
