### PR TITLE
Proposal for a new overview image for the starter modelling process

### PR DESCRIPTION
**Pull request by mploed**
I designed an alternative overview image for the starter modelling process which highlights the iterative nature of DDD.

Why do I propose this visualization:

- The usage of numbers like 1. Align 2. Discover 3. Decompose may imply some waterfall thinking in people not familiar with DDD
- I have been asked in customer workshop why I jump from 4. Connect directly to 7. Define sometimes for example
- This visualization also harmonizes better with the [model exploration whirlpool](https://www.domainlanguage.com/ddd/whirlpool/)

I also renamed 1. Align to "Grasp" because I think that an alignment between business model / user needs happens later on the the decomposition / connect / strategize / organize phases. Don't we use stuff like business model canvasses to get a better understanding to the business model and user needs? So we try to "grasp" them.

Keen to hear your feedback on this proposal / pull request.

### CODE REVIEW

**Comment by NTCoding** [comment]
Excellent @mploed. I think the visualisation is a huge step forward and I completely agree with your reasoning.

The original image was just an MVP based on the order of teaching in our workshops. I've been hoping for a while that somebody would create something better and you've done a superb job of it.

**Review by NTCoding — APPROVED** [review]

**Comment by emgsilva** [comment]
+1, I have to say that I struggled with similar challenges - this is not a sequence and having numbers makes people go into that mindset.... having this into such a form will allow for catering for the iterations and cycles we go through! Great job @mploed!

I really like the renaming of the first step to "Understand". This is a topic I am exploring currently (while looking at Systems Thinking and Sociotechnical Architecture and how to approach it - I will try to bring some of those ideas later they may add some good elements to the picture, still some things to roundup). Basically "Understanding" is about answering the "Why" questions from a "holistic perspective"... so I think this term is really good for this typically first step of the process. Indeed, alignment or "synthesis" happens on the following phases.

**Review by emgsilva — APPROVED** [review]

**Comment by emgsilva** [comment]
@mploed just noticed that we may also need to adjust the terminology changes (and remove the numbers) on the rest of the page sections... can you fix that?

**Comment by mploed** [comment]
@emgsilva yes I can

Would you like to change "Grasp" to "Understand"?

**Review by antmdvs — CHANGES_REQUESTED** [review]
Typo in subheading: "DDD ist"

**Comment by mploed** [comment]
Fixed the typo(s) and adjusted the README.md file. I also removed the ordering numbers from the text in order to stay consistend to the new overview image.

**Comment by NTCoding** [comment]
I've been using this image in my workshops recently and it's good! Ready to merge soon?

**Comment by mploed** [comment]
Yes, I would merge!

**Comment by emgsilva** [comment]
+1 for merge: this really is a great step to bring more clarity to the "flow of evolution".

**Pull request merged**
